"""
Consent capture — the moment an anonymous visitor becomes someone we may name.

Phase 4's first endpoint, and the gate everything after it depends on:
`consent-and-identity.md` §4 has the capture surface (badge, QR, kiosk, form)
show versioned copy, take a tier, and put a consent event on the bus "like any
other signal". This is that.

## What this does not do

It does not create a `Contact`, draw an `IDENTIFIED_AS` edge, or touch the graph
at all. That is `consumers/identity.py`'s job, downstream of the log.

The split is not tidiness. Asking for permission and acting on it are separate
decisions, and putting them in one function means the record of what somebody
agreed to is written by the same code that benefits from the answer. Keeping the
capture to "append the fact, exactly as stated" also means a deployment can
replay its whole consent history through a corrected identity consumer without
re-asking anybody.

It also makes the endpoint honest about failure: if the graph is down, consent
is still captured. A kiosk that cannot record a yes because a database it has
never heard of is unavailable would either lose the consent or, worse, proceed
anyway.

## Why `consentId` is required

Every producer on this bus supplies its own idempotency key
(`event-bus-spec.md` §2 — "event_id is supplied by the producer … if the POST
times out and the producer resends, the log dedupes it"). A capture surface is a
producer, and it is the one place where a duplicate is worst: two consent records
for one conversation, differing only in id, and no way afterwards to tell which
the person actually saw.

So the surface generates the id before it shows the copy, and a retry after a
timeout carries the same one. Generating it here instead would make a kiosk on
bad conference wifi produce a fresh consent for every retry.

## Tenant isolation

`tenantId` is never read from the body; it comes from the verified credential,
as everywhere else in this API.
"""

from __future__ import annotations

import datetime as dt
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app import repository
from app.auth.principal import Principal, get_principal
from app.consumers.ids import derive_event_id
from app.db import get_session
from app.schemas import EventIn, EventOut, _to_camel

router = APIRouter(prefix="/v1/consent", tags=["consent"])

CAPTURED = "consent.captured"
WITHDRAWN = "consent.withdrawn"


class CapturedContact(BaseModel):
    """The PII half, and the only PII in the payload.

    Every field optional: a badge scan may carry nothing at capture time, with
    the details arriving from the registry later. Everything outside this object
    is anonymous, which is what lets a deployment keep the consent record after
    erasing the person it was about.
    """

    model_config = ConfigDict(alias_generator=_to_camel, populate_by_name=True)

    email: str | None = Field(default=None, max_length=320)
    name: str | None = Field(default=None, max_length=200)
    company: str | None = Field(default=None, max_length=200)
    title: str | None = Field(default=None, max_length=200)


class ConsentIn(BaseModel):
    """What a capture surface POSTs. Mirrors `event-bus-spec.md` §3's pin."""

    model_config = ConfigDict(alias_generator=_to_camel, populate_by_name=True)

    #: Generated by the surface *before* the copy is shown. See the module
    #: docstring — this is the idempotency key, and a retry must reuse it.
    consent_id: str = Field(min_length=1, max_length=128)
    session_id: str = Field(min_length=1)
    #: The track this consent is about. Not a contact_id: there is no Contact
    #: yet, and creating one happens after the gate, never as part of asking.
    anon_id: str = Field(min_length=1)

    tier: Literal["T1", "T2", "T3"]
    basis: Literal["explicit_optin", "contract", "legitimate_interest"]

    #: The exact wording shown, versioned. Required, and the reason is in
    #: `consent-and-identity.md` §4: the tier says what somebody was asked for,
    #: this says what they read before agreeing, and it is the only thing that
    #: settles a withdrawal argued after the fact. A surface that cannot say
    #: which wording it displayed has not really captured consent.
    copy_version: str = Field(min_length=1, max_length=128)

    captured_by: str = Field(min_length=1, max_length=128)
    source: Literal["badge", "qr", "kiosk", "form", "manual"]

    #: When the person agreed, on the capturing surface's clock. Defaults to now
    #: rather than being required, because a kiosk's answer is "just now" and a
    #: required field there is one more thing to get wrong.
    captured_at: dt.datetime | None = None
    #: Null = the end of the activation (`consent-and-identity.md` §3).
    expires_at: dt.datetime | None = None

    contact: CapturedContact | None = None


class WithdrawalIn(BaseModel):
    """A withdrawal, from a kiosk, an operator, or an inbound erasure request.

    All three identifiers are optional and at least one is required, which looks
    sloppy and is not: the withdrawal has to work from whichever one the person
    in front of you actually has. A visitor at a kiosk knows their email, an
    erasure request names a Contact, and a mid-session change of mind at the
    capture surface knows only the track standing in front of it.
    """

    model_config = ConfigDict(alias_generator=_to_camel, populate_by_name=True)

    session_id: str = Field(min_length=1)
    consent_id: str | None = None
    contact_id: str | None = None
    anon_id: str | None = None
    reason: Literal["visitor_request", "erasure_request", "operator"] = "visitor_request"
    withdrawn_at: dt.datetime | None = None


@router.post(
    "",
    response_model=EventOut,
    status_code=status.HTTP_201_CREATED,
    summary="Record a consent, exactly as it was given",
)
async def capture(
    body: ConsentIn,
    principal: Principal = Depends(get_principal),
    session: AsyncSession = Depends(get_session),
) -> EventOut:
    """Append `consent.captured`. Nothing else happens here — see the module
    docstring.

    `get_principal` rather than `require_operator`: a kiosk runs on a device
    credential, and a device may write. Requiring an operator would mean every
    capture surface on the floor carried a human's token.
    """
    now = dt.datetime.now(dt.timezone.utc)
    captured_at = body.captured_at or now

    payload: dict = {
        "consent_id": body.consent_id,
        "anon_id": body.anon_id,
        "tier": body.tier,
        "basis": body.basis,
        "copy_version": body.copy_version,
        "captured_by": body.captured_by,
        "source": body.source,
        "captured_at": captured_at.isoformat(),
        "expires_at": body.expires_at.isoformat() if body.expires_at else None,
    }
    if body.contact is not None:
        # Omitted entirely rather than written as an object of nulls: "no
        # details were given" and "these details are blank" are different
        # statements about what a person handed over.
        contact = body.contact.model_dump(exclude_none=True)
        if contact:
            payload["contact"] = contact

    row, _ = await repository.append_event(
        session,
        EventIn(
            # Derived from the consent id, so the surface's retry and this
            # endpoint agree on what "the same capture" means without the
            # surface having to mint a second identifier for the same act.
            event_id=derive_event_id("consent", principal.tenant_id, body.consent_id),
            tenant_id=principal.tenant_id,
            session_id=body.session_id,
            type=CAPTURED,
            payload=payload,
            occurred_at=captured_at,
        ),
    )
    return EventOut.model_validate(row)


@router.post(
    "/withdraw",
    response_model=EventOut,
    status_code=status.HTTP_201_CREATED,
    summary="Record a withdrawal of consent",
)
async def withdraw(
    body: WithdrawalIn,
    principal: Principal = Depends(get_principal),
    session: AsyncSession = Depends(get_session),
) -> EventOut:
    """Append `consent.withdrawn`. The re-anonymiser does the rest.

    Same shape as capture and for the same reason: a withdrawal that depended on
    the graph being reachable would be a withdrawal that can fail at the moment
    it matters most. Recording it is unconditional; acting on it is a consumer's
    job, with the bus's retries and dead-lettering behind it.
    """
    subject = body.consent_id or body.contact_id or body.anon_id
    if subject is None:
        # A 422 with the reason, rather than a validator on the model: the rule
        # is about the three fields together, and the message is what tells a
        # kiosk author which of them they are expected to have.
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=(
                "a withdrawal must name at least one of consentId, contactId or "
                "anonId — whichever the person in front of you can be identified by"
            ),
        )

    withdrawn_at = body.withdrawn_at or dt.datetime.now(dt.timezone.utc)
    row, _ = await repository.append_event(
        session,
        EventIn(
            # Derived from the subject and the reason, deliberately *not* from
            # the timestamp. Withdrawing the same consent twice is one fact
            # stated twice, and a timestamped id would put both on the log for
            # the re-anonymiser to redo. Reason is in the key because an erasure
            # request is a wider act than a change of mind, not a repeat of it.
            event_id=derive_event_id(
                "consent_withdrawn", principal.tenant_id, subject, body.reason
            ),
            tenant_id=principal.tenant_id,
            session_id=body.session_id,
            type=WITHDRAWN,
            payload={
                "consent_id": body.consent_id,
                "contact_id": body.contact_id,
                "anon_id": body.anon_id,
                "reason": body.reason,
                "withdrawn_at": withdrawn_at.isoformat(),
            },
            occurred_at=withdrawn_at,
        ),
    )
    return EventOut.model_validate(row)
