"""event bus schema

Hand-written, not autogenerated. The body is the literal SQL from
docs/event-bus-spec.md §2, so the schema Postgres ends up with is provably the
spec's rather than SQLAlchemy's interpretation of it.

The only departure: the spec writes `CREATE INDEX ON event_log (...)` without a
name. Postgres would auto-name those, and Alembic's autogenerate compares
indexes *by name* — so the names are spelled out here, and app/models.py uses
the exact same ones. Running `alembic revision --autogenerate` after this
applies must produce an empty migration; anything else means the models and this
file have drifted.

Revision ID: 0001
Revises:
Create Date: 2026-07-28
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE event_log (
          seq          BIGSERIAL PRIMARY KEY,     -- monotonic order (replay cursor)
          event_id     UUID UNIQUE NOT NULL,      -- producer-assigned; dedupe key
          tenant_id    TEXT NOT NULL,
          session_id   TEXT NOT NULL,
          type         TEXT NOT NULL,             -- see event-bus-spec.md §3
          payload      JSONB NOT NULL,
          occurred_at  TIMESTAMPTZ NOT NULL,      -- when it happened (edge clock)
          recorded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute(
        "CREATE INDEX event_log_tenant_id_session_id_seq_idx "
        "ON event_log (tenant_id, session_id, seq);"
    )
    op.execute("CREATE INDEX event_log_type_idx ON event_log (type);")

    op.execute(
        """
        CREATE TABLE consumer_cursor (
          consumer     TEXT NOT NULL,
          tenant_id    TEXT NOT NULL,
          last_seq     BIGINT NOT NULL DEFAULT 0,
          updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (consumer, tenant_id)
        );
        """
    )

    op.execute(
        """
        CREATE TABLE dead_letter (
          id           BIGSERIAL PRIMARY KEY,
          consumer     TEXT NOT NULL,
          event_seq    BIGINT NOT NULL,
          error        TEXT NOT NULL,
          attempts     INT NOT NULL DEFAULT 0,
          created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
          resolved_at  TIMESTAMPTZ
        );
        """
    )


def downgrade() -> None:
    # Reverse order. No FKs between these three today, but keeping the order
    # honest costs nothing and matters the moment one is added.
    op.execute("DROP TABLE dead_letter;")
    op.execute("DROP TABLE consumer_cursor;")
    op.execute("DROP TABLE event_log;")
